export const COMMUNITIES  = [
  'Angular Bolivia',
  'Angular Colombia',
  'Ng Bogotá',
  'Ng Medellin',
  'Ng Popayán',
  'GDG Cochabamba',
  'GDG La Paz',
  'Angular Peru',
  'Angular Mexico',
  'Angular Chile',
  'Angular Costa Rica',
  'Angular Honduras',
  'Angular Quito',
  'She Codes Angular',
  'Angular Ecuador',
  'Angular Dominicana',
  'Angular Rome',
];
